<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="objects">

  <!-- 
    苹果模型 - 使用YCB数据集模型（Yale-CMU-Berkeley Object Set）
    支持使用YCB高质量mesh模型或简单几何形状作为后备
    模型来源：https://github.com/kwonathan/ycb_urdfs
  -->
  <!-- 修改默认值为world，调整默认Z坐标到桌面 -->
  <xacro:macro name="apple"
    params="name:='apple'
            parent_link:='world'
            xyz:='0.15 0.1 0.275'
            rpy:='0 0 0'
            radius:=0.04
            use_local_mesh:=true">

    <!-- 苹果主体 - 使用YCB模型 -->
    <link name="${name}_link">
      <visual>
        <!-- YCB模型的origin偏移，用于将mesh原点调整到物体中心 -->
        <origin xyz="-0.013105802251075094 0.03861242636253375 -0.3633673271131293" rpy="0 0 0"/>
        <geometry>
          <xacro:if value="${use_local_mesh}">
            <!-- 使用YCB模型的mesh文件，scale=6缩小模型尺寸 -->
            <mesh filename="package://openarm_description/meshes/environment/apple/meshes/textured.dae" scale="1 1 1"/>
          </xacro:if>
          <xacro:unless value="${use_local_mesh}">
            <!-- 使用简单球体几何形状 -->
            <sphere radius="${radius}"/>
          </xacro:unless>
        </geometry>
        <xacro:if value="${use_local_mesh}">
          <!-- 使用mesh时不需要材质 -->
        </xacro:if>
        <xacro:unless value="${use_local_mesh}">
          <material name="apple_material">
            <color rgba="0.9 0.1 0.1 1"/>
          </material>
        </xacro:unless>
      </visual>
      <collision>
        <!-- YCB模型的origin偏移，用于将mesh原点调整到物体中心 -->
        <origin xyz="-0.013105802251075094 0.03861242636253375 -0.3633673271131293" rpy="0 0 0"/>
        <geometry>
          <xacro:if value="${use_local_mesh}">
            <!-- 使用YCB模型的碰撞模型（vhacd优化过的mesh） -->
            <mesh filename="package://openarm_description/meshes/environment/apple/meshes/textured_vhacd.obj" scale="1 1 1"/>
          </xacro:if>
          <xacro:unless value="${use_local_mesh}">
            <sphere radius="${radius * 1.05}"/>
          </xacro:unless>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <xacro:if value="${use_local_mesh}">
          <!-- YCB模型的质量和惯性参数（使用更合理的苹果质量） -->
          <mass value="0.2"/>
          <inertia ixx="0.0002" ixy="0" ixz="0"
                   iyy="0.0002" iyz="0"
                   izz="0.0002"/>
        </xacro:if>
        <xacro:unless value="${use_local_mesh}">
          <!-- 简单几何形状的质量和惯性参数 -->
          <mass value="0.18"/>
          <inertia ixx="0.00012" ixy="0" ixz="0"
                   iyy="0.00012" iyz="0"
                   izz="0.00012"/>
        </xacro:unless>
      </inertial>
    </link>

    <!-- 苹果茎 - 仅在非mesh模式下显示 -->
    <xacro:if value="${use_local_mesh}">
      <!-- 使用mesh时不显示茎 -->
    </xacro:if>
    <xacro:unless value="${use_local_mesh}">
      <link name="${name}_stem_link">
        <visual>
          <origin xyz="0 0 ${radius}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${radius*0.1}" length="${radius*0.3}"/>
          </geometry>
          <material name="stem_material">
            <color rgba="0.3 0.6 0.2 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 ${radius}" rpy="0 0 0"/>
          <geometry>
            <cylinder radius="${radius*0.1}" length="${radius*0.3}"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 ${radius}" rpy="0 0 0"/>
          <mass value="0.001"/>
          <inertia ixx="0.000001" ixy="0" ixz="0"
                   iyy="0.000001" iyz="0"
                   izz="0.000001"/>
        </inertial>
      </link>

      <joint name="${name}_stem_joint" type="fixed">
        <parent link="${name}_link"/>
        <child link="${name}_stem_link"/>
        <origin xyz="0 0 ${radius}" rpy="0 0 0"/>
      </joint>
    </xacro:unless>

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${name}_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

  </xacro:macro>

  <!-- 
    香蕉模型 - 使用YCB数据集模型（Yale-CMU-Berkeley Object Set）
    支持使用YCB高质量mesh模型或简单几何形状作为后备
    模型来源：https://github.com/kwonathan/ycb_urdfs
  -->
  <!-- 修改默认值为world，调整默认Z坐标到桌面 -->
  <xacro:macro name="banana"
    params="name:='banana'
            parent_link:='world'
            xyz:='-0.1 0.05 0.275'
            rpy:='0 0 1.73'
            length:=0.18
            radius:=0.02
            use_local_mesh:=true">

    <!-- 香蕉主体 - 使用YCB模型 -->
    <link name="${name}_link">
      <visual>
        <!-- YCB模型的origin偏移，用于将mesh原点调整到物体中心 -->
        <origin xyz="0.09936102440002159 -0.04072679186328214 -0.1712688923116843" rpy="0 0 0"/>
        <geometry>
          <xacro:if value="${use_local_mesh}">
            <!-- 使用YCB模型的mesh文件，scale=6缩小模型尺寸 -->
            <mesh filename="package://openarm_description/meshes/environment/banana/meshes/textured.dae" scale="1 1 1"/>
          </xacro:if>
          <xacro:unless value="${use_local_mesh}">
            <!-- 使用简单圆柱体几何形状 -->
            <cylinder radius="${radius}" length="${length}"/>
          </xacro:unless>
        </geometry>
        <xacro:if value="${use_local_mesh}">
          <!-- 使用mesh时不需要材质 -->
        </xacro:if>
        <xacro:unless value="${use_local_mesh}">
          <material name="banana_material">
            <color rgba="0.95 0.85 0.2 1"/>
          </material>
        </xacro:unless>
      </visual>
      <collision>
        <!-- YCB模型的origin偏移，用于将mesh原点调整到物体中心 -->
        <origin xyz="0.09936102440002159 -0.04072679186328214 -0.1712688923116843" rpy="0 0 0"/>
        <geometry>
          <xacro:if value="${use_local_mesh}">
            <!-- 使用YCB模型的碰撞模型（vhacd优化过的mesh） -->
            <mesh filename="package://openarm_description/meshes/environment/banana/meshes/textured_vhacd.obj" scale="1 1 1"/>
          </xacro:if>
          <xacro:unless value="${use_local_mesh}">
            <cylinder radius="${radius * 1.05}" length="${length * 1.05}"/>
          </xacro:unless>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <xacro:if value="${use_local_mesh}">
          <!-- YCB模型的质量和惯性参数（使用更合理的香蕉质量） -->
          <mass value="0.12"/>
          <inertia ixx="0.00008" ixy="0" ixz="0"
                   iyy="0.00008" iyz="0"
                   izz="0.00015"/>
        </xacro:if>
        <xacro:unless value="${use_local_mesh}">
          <!-- 简单几何形状的质量和惯性参数 -->
          <mass value="0.12"/>
          <inertia ixx="0.00008" ixy="0" ixz="0"
                   iyy="0.00008" iyz="0"
                   izz="0.00015"/>
        </xacro:unless>
      </inertial>
    </link>

    <!-- 香蕉顶部（较细的一端） - 仅在非mesh模式下显示 -->
    <xacro:if value="${use_local_mesh}">
      <!-- 使用mesh时不显示顶部 -->
    </xacro:if>
    <xacro:unless value="${use_local_mesh}">
      <link name="${name}_tip_link">
        <visual>
          <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
          <geometry>
            <sphere radius="${radius*0.6}"/>
          </geometry>
          <material name="banana_tip_material">
            <color rgba="0.9 0.8 0.15 1"/>
          </material>
        </visual>
        <collision>
          <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
          <geometry>
            <sphere radius="${radius*0.6}"/>
          </geometry>
        </collision>
        <inertial>
          <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
          <mass value="0.01"/>
          <inertia ixx="0.000001" ixy="0" ixz="0"
                   iyy="0.000001" iyz="0"
                   izz="0.000001"/>
        </inertial>
      </link>

      <joint name="${name}_tip_joint" type="fixed">
        <parent link="${name}_link"/>
        <child link="${name}_tip_link"/>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
      </joint>
    </xacro:unless>

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${name}_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

  </xacro:macro>

  <!-- 
    物体组宏 - 用于同时创建多个物体
    使用YCB数据集的高质量3D模型，提供更真实的视觉效果和物理特性
  -->
  <!-- 修改默认值为world，调整默认Z坐标到桌面 -->
  <xacro:macro name="objects_group"
    params="parent_link:='world'
            enable_apple:=true
            enable_banana:=true
            apple_xyz:='0.15 0.1 0.275'
            banana_xyz:='-0.1 0.05 0.275'
            use_local_mesh:=true">

    <xacro:if value="${enable_apple}">
      <xacro:apple name="apple" 
                   parent_link="${parent_link}" 
                   xyz="${apple_xyz}"
                   use_local_mesh="${use_local_mesh}"/>
    </xacro:if>

    <xacro:if value="${enable_banana}">
      <xacro:banana name="banana" 
                    parent_link="${parent_link}" 
                    xyz="${banana_xyz}"
                    use_local_mesh="${use_local_mesh}"/>
    </xacro:if>

  </xacro:macro>

</robot>